package demo.campproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class campModel implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Record Id")
   private java.lang.String recordId;
   @org.kie.api.definition.type.Label(value = "User Id")
   private java.lang.String userId;
   @org.kie.api.definition.type.Label(value = "Adjudocator Id")
   private java.lang.String adjudicatorId;

   public campModel()
   {
   }

   public java.lang.String getRecordId()
   {
      return this.recordId;
   }

   public void setRecordId(java.lang.String recordId)
   {
      this.recordId = recordId;
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   
   public java.lang.String getAdjudicatorId()
   {
      return this.adjudicatorId;
   }

   public void setAdjudicatorId(java.lang.String adjudicatorId)
   {
      this.userId = adjudicatorId;
   }
   
   public campModel(java.lang.String recordId, java.lang.String userId,java.lang.String adjudicatorId)
   {
      this.recordId = recordId;
      this.userId = userId;
      this.adjudicatorId= adjudicatorId;
   }

}